In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
from keras.models import Sequential
from keras.layers import Dense, Conv2D , Conv1D, MaxPool1D, MaxPool2D , Flatten , Dropout , BatchNormalization
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
import pandas as pd
from sklearn.preprocessing import LabelBinarizer
import joblib
import os
from PIL import Image
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import re
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, MaxPooling2D, GlobalAveragePooling2D, BatchNormalization, Dropout, Dense, Flatten, Input, Lambda
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ModelCheckpoint
from keras.callbacks import ReduceLROnPlateau , EarlyStopping
from tensorflow.keras.optimizers import Adam 
from tensorflow.keras import regularizers
import tensorflow as tf
from keras.utils.np_utils import to_categorical # convert to one-hot-encoding

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import albumentations as A

transform = A.Compose([
    A.RandomBrightnessContrast(),
    A.Affine(scale=[0.8,1.2],translate_percent=0.05, shear=0.2, keep_ratio=True, p=0.5),
    A.Rotate(limit=10)
])

## Without mediapipe

#### Read image and convert it to 28x28 matrix:

In [ ]:
folder_name = '/content/drive/MyDrive/IS4242/data' #might be different for different people
path = folder_name
img_list = []
label_list = []
txt = 'abcdefghiklmnopqrstuvwxy'

for i in tqdm(range(len(os.listdir(path)))):
  filename = os.listdir(path)[i]
  if filename.endswith(('.jpg','.png')):
      label_name = re.split(r'[-_]', filename)[0].lower()
      if label_name not in txt:
        continue
      label_list.append(label_name)
      img = Image.open(os.path.join(path, filename))
      img = img.resize((28, 28), Image.ANTIALIAS)
      img = img.convert('L')
      img_array = np.array(img)
      
      img_list.append(img_array)


In [ ]:
X = np.array(img_list)

y = np.array(label_list)
y = np.array(list(map(lambda x:txt.find(x), y)))
y = to_categorical(y)

#### Train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

output_dir = '/content/drive/MyDrive/IS4242/dump/'
joblib.dump(X, output_dir+'X.pkl')
joblib.dump(y, output_dir+'y.pkl')

(634, 28, 28)
(159, 28, 28)
(634, 24)
(159, 24)


['/content/drive/MyDrive/IS4242/dump/y.pkl']

#### Augmentation only on train data

In [ ]:
augmented_X = []
augmented_y = []
for i in range(len(X_train)):
  for j in (range(10)):
      transformed = transform(image=X_train[i])
      augmented_X.append(transformed['image'])
      augmented_y.append(y_train[i])

augmented_X = np.array(augmented_X)
augmented_y = np.array(augmented_y)
X_train = np.concatenate([X_train,augmented_X])
y_train = np.concatenate([y_train,augmented_y])

output_dir = '/content/drive/MyDrive/IS4242/dump/'
joblib.dump(augmented_X, output_dir+'augmented_X.pkl')
joblib.dump(augmented_y, output_dir+'augmented_y.pkl')

['/content/drive/MyDrive/IS4242/dump/augmented_y.pkl']

In [ ]:
print(X_train.shape)
print(y_train.shape)

(6974, 28, 28)
(6974, 24)


#### Reshape and divide the pixels by 255

In [ ]:
X_train = X_train/255.0
X_test = X_test/255.0
X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(6974, 28, 28, 1)
(159, 28, 28, 1)
(6974, 24)
(159, 24)


#### CNN with augmentation

In [ ]:
datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
        zoom_range = 0.1, # Randomly zoom image 
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=False,
        brightness_range=[0.8,1.2],
        vertical_flip=False)


datagen.fit(X_train)

In [ ]:
# Set a learning rate annealer
learning_rate_reduction = ReduceLROnPlateau(monitor='val_accuracy', 
                                            patience=3, 
                                            verbose=1, 
                                            factor=0.5, 
                                            min_lr=0.00001)

In [ ]:
# architecture
# Set the CNN model 

model = Sequential()
model.add(Conv2D(filters = 128, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu', input_shape = (28,28,1)))
model.add(Conv2D(filters = 128, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(BatchNormalization())
model.add(Dropout(0.25))
model.add(Conv2D(filters = 64, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(Conv2D(filters = 64, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(MaxPool2D(pool_size=(2,2), strides=(2,2)))
model.add(BatchNormalization())
model.add(Dropout(0.25))
model.add(Conv2D(filters = 32, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(Conv2D(filters = 32, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D((2,2) , strides = 2 , padding = 'same'))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(512, activation = "relu"))
model.add(Dense(256, activation = "relu"))
model.add(Dense(24, activation = "softmax"))

model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_42 (Conv2D)          (None, 28, 28, 32)        832       
                                                                 
 conv2d_43 (Conv2D)          (None, 28, 28, 32)        25632     
                                                                 
 max_pooling2d_21 (MaxPoolin  (None, 14, 14, 32)       0         
 g2D)                                                            
                                                                 
 batch_normalization_21 (Bat  (None, 14, 14, 32)       128       
 chNormalization)                                                
                                                                 
 dropout_28 (Dropout)        (None, 14, 14, 32)        0         
                                                                 
 conv2d_44 (Conv2D)          (None, 14, 14, 64)       

In [ ]:
epochs = 30
batch_size = 32


model_checkpoint_callback = ModelCheckpoint(
    filepath="best.h5",
    monitor='val_accuracy', 
    verbose=1, 
    save_best_only=True, 
    mode='max')

es = EarlyStopping(monitor="val_loss", mode="min", verbose=1, patience=10)

# Fit the model
history = model.fit_generator(datagen.flow(X_train, y_train, batch_size=batch_size),
                              epochs = epochs, validation_data = (X_test, y_test),steps_per_epoch=X_train.shape[0] // batch_size,
                              verbose = 1,   callbacks=[model_checkpoint_callback,learning_rate_reduction,es])

Epoch 1/30


<ipython-input-169-021abc8791b3>:15: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history = model.fit_generator(datagen.flow(X_train, y_train, batch_size=batch_size),


54/54 [==============================] - ETA: 0s - loss: 3.4244 - accuracy: 0.0540
Epoch 1: val_accuracy improved from -inf to 0.01887, saving model to best.h5
54/54 [==============================] - 81s 1s/step - loss: 3.4244 - accuracy: 0.0540 - val_loss: 3.2231 - val_accuracy: 0.0189 - lr: 0.0010
Epoch 2/30
54/54 [==============================] - ETA: 0s - loss: 3.1336 - accuracy: 0.0711
Epoch 2: val_accuracy improved from 0.01887 to 0.06289, saving model to best.h5
54/54 [==============================] - 82s 2s/step - loss: 3.1336 - accuracy: 0.0711 - val_loss: 3.2113 - val_accuracy: 0.0629 - lr: 0.0010
Epoch 3/30
54/54 [==============================] - ETA: 0s - loss: 3.0425 - accuracy: 0.0963
Epoch 3: val_accuracy did not improve from 0.06289
54/54 [==============================] - 77s 1s/step - loss: 3.0425 - accuracy: 0.0963 - val_loss: 3.2515 - val_accuracy: 0.0440 - lr: 0.0010
Epoch 4/30
54/54 [==============================] - ETA: 0s - loss: 2.8801 - accuracy: 0.1382
E

In [ ]:
results = model.predict(X_test)
y_pred = np.argmax(results,axis = 1) 
y_true = np.argmax(y_test,axis = 1) 


5/5 [==============================] - 0s 71ms/step


#### Results

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.25      0.40      0.31         5
           2       0.83      0.42      0.56        12
           3       0.50      0.40      0.44         5
           4       0.38      0.43      0.40         7
           5       0.57      0.67      0.62         6
           6       0.00      0.00      0.00         5
           7       0.25      0.09      0.13        11
           8       0.75      0.60      0.67         5
           9       0.75      0.50      0.60         6
          10       0.67      0.67      0.67         3
          11       0.00      0.00      0.00         3
          12       0.11      0.20      0.14         5
          13       0.57      0.50      0.53         8
          14       0.67      0.57      0.62         7
          15       0.33      0.17      0.22         6
          16       0.29      0.25      0.27         8
          17       0.50    

#### Prediction and evaluation

In [ ]:
img = Image.open('m.png')
img = img.resize((28, 28), Image.ANTIALIAS)
img = img.convert('L')
img_array = np.array(img)
img_array = img_array/255.0
img_array = img_array.reshape(-1, 28, 28, 1)

In [ ]:
results = model.predict(img_array)
y_pred = np.argmax(results,axis = 1)
txt[y_pred[0]]

1/1 [==============================] - 0s 46ms/step


'm'

#### After hyperparameter tuning, train it with the whole data

In [ ]:
output_dir = '/content/drive/MyDrive/IS4242/dump/'
X = joblib.load(output_dir+'X.pkl')
y = joblib.load(output_dir+'y.pkl')

In [ ]:
augmentX = []
augmenty = []
for i in range(len(X)):
  for j in (range(10)):
      transformed = transform(image=X[i])
      augmentX.append(transformed['image'])
      augmenty.append(y[i])

augmentX = np.array(augmentX)
augmenty = np.array(augmenty)
X = np.concatenate([X,augmentX])
y = np.concatenate([y,augmenty])

In [ ]:
X = X/255.0
X = X.reshape(-1, 28, 28, 1)

In [ ]:
datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=10,  # randomly rotate images in the range (degrees, 0 to 180)
        zoom_range = 0.1, # Randomly zoom image 
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=False,
        brightness_range=[0.8,1.2],
        vertical_flip=False)


datagen.fit(X)

In [ ]:
model = Sequential()
model.add(Conv2D(filters = 32, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu', input_shape = (28,28,1)))
model.add(Conv2D(filters = 32, kernel_size = (5,5),padding = 'Same', 
                 activation ='relu'))
model.add(MaxPool2D(pool_size=(2,2) , padding = 'same'))
model.add(BatchNormalization())
model.add(Dropout(0.25))
model.add(Conv2D(filters = 64, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(Conv2D(filters = 64, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(MaxPool2D(pool_size=(2,2) , padding = 'same'))
model.add(BatchNormalization())
model.add(Dropout(0.25))
model.add(Conv2D(filters = 128, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(Conv2D(filters = 128, kernel_size = (3,3),padding = 'Same', 
                 activation ='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D((2,2) , padding = 'same'))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(256, activation = "relu"))
model.add(Dense(512, activation = "relu"))
model.add(Dense(24, activation = "softmax"))

model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
epochs = 30
batch_size = 64

# Fit the model
model.compile(optimizer=Adam(lr=0.001), loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit_generator(datagen.flow(X, y, batch_size=batch_size),epochs = epochs)

In [ ]:
img = Image.open('m.png')
img = img.resize((28, 28), Image.ANTIALIAS)
img = img.convert('L')
img_array = np.array(img)
img_array = img_array/255.0
img_array = img_array.reshape(-1, 28, 28, 1)

In [ ]:
results = model.predict(img_array)
y_pred = np.argmax(results,axis = 1)
txt[y_pred[0]]

1/1 [==============================] - 0s 46ms/step


'm'

## Using mediapipe

In [ ]:
!pip install mediapipe

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.6/33.6 MB 42.0 MB/s eta 0:00:00


In [ ]:
# For capturing hand coordinates
import cv2
import tensorflow as tf
import mediapipe as mp

In [ ]:
# For processing data
import csv
import os
import numpy as np
import pandas as pd
from tqdm import tqdm 
import re

#### Convert image data to matrix

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount = True)

Mounted at /content/drive


In [ ]:
import albumentations as A

transform = A.Compose([
    A.RandomBrightnessContrast(),
    A.Affine(scale=[0.8,1.2],translate_percent=0.05, shear=0.2, keep_ratio=True, p=0.5),
    A.Rotate(limit=10)
])

In [ ]:
folder_name = '/content/drive/MyDrive/IS4242/data' #might be different for different people
path = folder_name
img_list = []
label_list = []
txt = 'abcdefghiklmnopqrstuvwxy'

for i in tqdm(range(len(os.listdir(path)))):
  filename = os.listdir(path)[i]
  if filename.endswith(('.jpg','.png')):
      label_name = re.split(r'[-_]', filename)[0].lower()
      if label_name not in txt:
        continue
      label_list.append(label_name)
      img = Image.open(os.path.join(path, filename))
      img = img.resize((224, 224), Image.ANTIALIAS) # bigger size
      img = img.convert('L')
      img_array = np.array(img)
      
      img_list.append(img_array)

X = np.array(img_list)

y = np.array(label_list)
y = np.array(list(map(lambda x:txt.find(x), y)))
y = to_categorical(y)

output_dir = '/content/drive/MyDrive/IS4242/dump/'
joblib.dump(X,output_dir+'X_224.pkl')
joblib.dump(y,output_dir+'y_224.pkl')


 16%|█▌        | 196/1221 [00:26<03:02,  5.63it/s]

In [ ]:
output_dir = '/content/drive/MyDrive/IS4242/dump/'
X = joblib.load(output_dir+'X_224.pkl')
y = joblib.load(output_dir+'y_224.pkl')

In [ ]:
len(X)

817

#### Train test split

In [ ]:
from sklearn.model_selection import train_test_split

# We will take 33% from 1000 for our test data.
# Recommended value 80:20, 67:33, 50:50
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### Augmentation only on train data

In [ ]:
X_train

array([[[212, 215, 214, ..., 220, 217, 209],
        [227, 218, 213, ..., 212, 208, 217],
        [185, 174, 181, ..., 164, 197, 205],
        ...,
        [232, 232, 232, ..., 145, 129, 148],
        [232, 232, 232, ..., 150, 138, 138],
        [232, 232, 232, ..., 159, 129, 124]],

       [[147, 148, 149, ..., 142, 142, 143],
        [147, 148, 149, ..., 141, 141, 142],
        [147, 148, 149, ..., 144, 144, 145],
        ...,
        [140, 139, 139, ..., 133, 134, 133],
        [140, 139, 139, ..., 133, 134, 133],
        [140, 139, 139, ..., 131, 133, 133]],

       [[183, 182, 181, ..., 175, 172, 175],
        [183, 180, 180, ..., 174, 174, 175],
        [181, 181, 181, ..., 174, 174, 174],
        ...,
        [171, 171, 171, ...,  32,  33,  33],
        [172, 171, 171, ...,  29,  28,  28],
        [171, 173, 173, ...,  28,  28,  29]],

       ...,

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0

In [ ]:
augmented_X = []
augmented_y = []
for i in range(len(X_train)):
  for j in (range(10)):
      transformed = transform(image=X_train[i])
      augmented_X.append(transformed['image'])
      augmented_y.append(y_train[i])

augmented_X = np.array(augmented_X)
augmented_y = np.array(augmented_y)
X_train = np.concatenate([X_train,augmented_X])
y_train = np.concatenate([y_train,augmented_y])

#### Generate dataset of hand points

In [ ]:
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands

In [ ]:
data = []
labels = []

In [ ]:
count = 0
with mp_hands.Hands(static_image_mode =True, max_num_hands = 2, min_detection_confidence=0.5) as hands:
    for i in tqdm(range(len(X_train))):
        # Load the image and extract its features
            results = hands.process(cv2.cvtColor(cv2.flip(X_train[i],1), cv2.COLOR_BGR2RGB))
            try:
                # Extract Hand landmarks
                for hand_landmark in results.multi_hand_landmarks:
                    right_hand = hand_landmark.landmark
                right_hand_row = list(np.array([[landmark.x, landmark.y] for landmark in right_hand]).flatten())
                # Concate rows
                row = right_hand_row

                # Extract the label from the image filename (e.g. "A.jpg")
                label = y_train[i]

                data.append(row)
                labels.append(label)
                print(row, label)
            except Exception as e:
                count += 1
                continue


Output hidden; open in https://colab.research.google.com to view.

In [ ]:
count

4730

In [ ]:
pd.DataFrame(data)

0         1         2         3         4         5         6   \
0     0.570230  0.700385  0.460918  0.601834  0.385230  0.526549  0.322623   
1     0.446183  0.796893  0.341452  0.681229  0.304357  0.500339  0.314089   
2     0.554823  0.467337  0.477951  0.500206  0.370337  0.497704  0.303738   
3     0.421717  0.593616  0.332333  0.543942  0.278878  0.457589  0.282298   
4     0.651359  0.619728  0.656911  0.514619  0.602316  0.457691  0.539696   
...        ...       ...       ...       ...       ...       ...       ...   
2448  0.583231  0.452619  0.539714  0.455225  0.495395  0.492904  0.479851   
2449  0.556153  0.509525  0.514526  0.529332  0.459658  0.563573  0.428268   
2450  0.583231  0.452619  0.539714  0.455225  0.495395  0.492904  0.479851   
2451  0.583231  0.452619  0.539714  0.455225  0.495395  0.492904  0.479851   
2452  0.596306  0.457798  0.557114  0.472554  0.511320  0.513201  0.491459   

            7         8         9   ...        32        33        34  \
0     0.470859  0.301588  0.408549  ...  0.434779  0.504095  0.549578   
1     0.366598  0.315794  0.253817  ...  0.488412  0.601652  0.734732   
2     0.458727  0.319072  0.396847  ...  0.466813  0.410920  0.478718   
3     0.384428  0.314716  0.334537  ...  0.391403  0.521059  0.528068   
4     0.429281  0.491382  0.435781  ...  0.391995  0.521948  0.437633   
...        ...       ...       ...  ...       ...       ...       ...   
2448  0.551855  0.483757  0.602373  ...  0.545168  0.576425  0.487555   
2449  0.608088  0.417417  0.649978  ...  0.471311  0.668249  0.432259   
2450  0.551855  0.483757  0.602373  ...  0.545168  0.576425  0.487555   
2451  0.551855  0.483757  0.602373  ...  0.545168  0.576425  0.487555   
2452  0.567501  0.487846  0.613706  ...  0.555029  0.575449  0.487250   

            35        36        37        38        39        40        41  
0     0.469310  0.416643  0.467967  0.423916  0.518278  0.466331  0.533848  
1     0.564161  0.699286  0.469736  0.620621  0.544259  0.574593  0.615079  
2     0.277710  0.441688  0.218711  0.420079  0.179862  0.393535  0.143242  
3     0.395230  0.475645  0.423229  0.459146  0.468935  0.459199  0.488524  
4     0.637292  0.367256  0.589515  0.384333  0.575371  0.412115  0.575475  
...        ...       ...       ...       ...       ...       ...       ...  
2448  0.524171  0.515908  0.578480  0.545968  0.580548  0.566784  0.575146  
2449  0.565127  0.447259  0.629455  0.473636  0.645954  0.497372  0.653503  
2450  0.524171  0.515908  0.578480  0.545968  0.580548  0.566784  0.575146  
2451  0.524171  0.515908  0.578480  0.545968  0.580548  0.566784  0.575146  
2452  0.520229  0.510673  0.578672  0.541977  0.585190  0.565311  0.583080  

[2453 rows x 42 columns]

In [ ]:
import joblib

output_dir = f"/content/drive/MyDrive/IS4242/dump/"
joblib.dump(data, output_dir+'data_svm_train.pkl')
joblib.dump(labels, output_dir+'labels_svm_train.pkl')

['/content/drive/MyDrive/IS4242/dump/labels_svm_train.pkl']

In [ ]:
from sklearn.preprocessing import StandardScaler
import joblib

scaler = StandardScaler().fit(data)

output_dir = f"/content/drive/MyDrive/IS4242/dump/"
joblib.dump(scaler, output_dir+'scaler_svm.pkl')



['/content/drive/MyDrive/IS4242/dump/scaler_svm.pkl']

In [ ]:
import joblib
output_dir = f"/content/drive/MyDrive/IS4242/dump/"
data = joblib.load(output_dir+'data_knn_2.pkl')
labels = joblib.load(output_dir+'labels_knn_2.pkl')

In [ ]:
test_data = []
test_label = []
count = 0
with mp_hands.Hands(static_image_mode =True, max_num_hands = 2, min_detection_confidence=0.5) as hands:
    for i in tqdm(range(len(X_test))):
        # Load the image and extract its features
            results = hands.process(cv2.cvtColor(cv2.flip(X_test[i],1), cv2.COLOR_BGR2RGB))
            try:
                # Extract Hand landmarks
                for hand_landmark in results.multi_hand_landmarks:
                    right_hand = hand_landmark.landmark
                right_hand_row = list(np.array([[landmark.x, landmark.y] for landmark in right_hand]).flatten())
                # Concate rows
                row = right_hand_row

                # Extract the label from the image filename (e.g. "A.jpg")
                label = y_test[i]

                test_data.append(row)
                test_label.append(label)
                print(row, label)
            except Exception as e:
                count += 1
                continue

  3%|▎         | 5/164 [00:00<00:07, 22.52it/s]

[0.5210281014442444, 0.641315221786499, 0.39546293020248413, 0.5578718781471252, 0.3307020962238312, 0.3800443112850189, 0.3052407503128052, 0.24902814626693726, 0.2702046036720276, 0.1634766012430191, 0.41695016622543335, 0.2820096015930176, 0.4198142886161804, 0.16589711606502533, 0.42496901750564575, 0.27493152022361755, 0.43036800622940063, 0.339459091424942, 0.5108478665351868, 0.2845029830932617, 0.5148842334747314, 0.17844367027282715, 0.4996938705444336, 0.3112812340259552, 0.49929216504096985, 0.34388941526412964, 0.5973529815673828, 0.31039708852767944, 0.6130174398422241, 0.20091238617897034, 0.5859422087669373, 0.32097747921943665, 0.5842393040657043, 0.3630259037017822, 0.6818413734436035, 0.3520607650279999, 0.6982240676879883, 0.2732140123844147, 0.6630502939224243, 0.35034728050231934, 0.6547291278839111, 0.3847343325614929] [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5496582388877869, 0.6345279216766357, 0.47247281670570374, 0.625109791

  7%|▋         | 11/164 [00:00<00:06, 23.93it/s]

[0.5303622484207153, 0.7261391878128052, 0.3620838522911072, 0.6153806447982788, 0.2671659290790558, 0.40738582611083984, 0.22772908210754395, 0.24531611800193787, 0.17089855670928955, 0.12447883188724518, 0.40584099292755127, 0.294745534658432, 0.34948059916496277, 0.20392224192619324, 0.34238922595977783, 0.3307180404663086, 0.36016517877578735, 0.4387580454349518, 0.5203278064727783, 0.30517739057540894, 0.4636331796646118, 0.20133087038993835, 0.451718270778656, 0.3622964024543762, 0.46842825412750244, 0.47976988554000854, 0.6406235694885254, 0.32791975140571594, 0.569840133190155, 0.22479650378227234, 0.5453921556472778, 0.3856639564037323, 0.5597202777862549, 0.5043128728866577, 0.764388918876648, 0.36453112959861755, 0.6879178285598755, 0.2666337490081787, 0.6525718569755554, 0.3518322706222534, 0.6621406674385071, 0.42191678285598755] [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.5895628929138184, 0.7734596133232117, 0.6003317832946777, 0.66376382

 13%|█▎        | 22/164 [00:00<00:04, 29.03it/s]

[0.5834823846817017, 0.6552193760871887, 0.48293307423591614, 0.6472676992416382, 0.368147075176239, 0.5931648015975952, 0.2746767997741699, 0.5641045570373535, 0.1981460154056549, 0.5506763458251953, 0.43822523951530457, 0.4367946982383728, 0.41417595744132996, 0.3389350175857544, 0.4004226326942444, 0.27617865800857544, 0.3889698386192322, 0.21981802582740784, 0.5112353563308716, 0.42563605308532715, 0.5319530963897705, 0.4108789563179016, 0.5414940118789673, 0.4969882369041443, 0.5372001528739929, 0.54562908411026, 0.5839648842811584, 0.4390241503715515, 0.600899338722229, 0.45438238978385925, 0.5944684743881226, 0.534484326839447, 0.5753219127655029, 0.5707814693450928, 0.6487951278686523, 0.4659665524959564, 0.6620150804519653, 0.4685323238372803, 0.6482803821563721, 0.530033528804779, 0.6272431015968323, 0.5599023699760437] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 17%|█▋        | 28/164 [00:01<00:05, 26.01it/s]

[0.4693065881729126, 0.7965080738067627, 0.35549217462539673, 0.7332205176353455, 0.265140563249588, 0.5736970901489258, 0.18623408675193787, 0.47287237644195557, 0.09433645009994507, 0.4304591417312622, 0.4164010286331177, 0.4361959993839264, 0.4196837842464447, 0.35470879077911377, 0.4010630249977112, 0.4719112813472748, 0.38688138127326965, 0.5750529766082764, 0.5098876953125, 0.44328972697257996, 0.5148328542709351, 0.36993300914764404, 0.4689432382583618, 0.5057414174079895, 0.4459727704524994, 0.6072433590888977, 0.6030418872833252, 0.4714335799217224, 0.6481388807296753, 0.34800824522972107, 0.5886692404747009, 0.4126054644584656, 0.5374879837036133, 0.48368021845817566, 0.6816179156303406, 0.513637900352478, 0.7628151178359985, 0.40982770919799805, 0.813788890838623, 0.3480430245399475, 0.8572395443916321, 0.28639519214630127] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0.4863141179084778, 0.5798488855361938, 0.4231042265892029, 0.5375117659568787

 21%|██        | 34/164 [00:01<00:04, 26.25it/s]

[0.5200693607330322, 0.6173232793807983, 0.4715971350669861, 0.5202031135559082, 0.46173185110092163, 0.41925662755966187, 0.4509440064430237, 0.35445383191108704, 0.4354439377784729, 0.31707361340522766, 0.5472732782363892, 0.33151060342788696, 0.5011919736862183, 0.2148597240447998, 0.44061627984046936, 0.21936923265457153, 0.4116023778915405, 0.26090845465660095, 0.5658331513404846, 0.3655824065208435, 0.41657933592796326, 0.33804383873939514, 0.407459557056427, 0.40558937191963196, 0.45104876160621643, 0.4349362254142761, 0.5598301291465759, 0.4165858030319214, 0.4078504741191864, 0.40815383195877075, 0.4137592017650604, 0.4646478593349457, 0.45712316036224365, 0.4791170358657837, 0.5364784002304077, 0.4719412326812744, 0.41882359981536865, 0.474730908870697, 0.42050623893737793, 0.5136706829071045, 0.45777231454849243, 0.5247096419334412] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0.5108542442321777, 0.7275295853614807, 0.461174339056015, 0.68713730

 24%|██▍       | 40/164 [00:01<00:04, 25.91it/s]

[0.5616580843925476, 0.5504832863807678, 0.4989834129810333, 0.5522018074989319, 0.42193782329559326, 0.5029745697975159, 0.3802850842475891, 0.4397194981575012, 0.3781181573867798, 0.38586828112602234, 0.38769394159317017, 0.4060283303260803, 0.3418986201286316, 0.3476794958114624, 0.35956767201423645, 0.37088409066200256, 0.3917556405067444, 0.39991265535354614, 0.45788171887397766, 0.38572657108306885, 0.43143054842948914, 0.3297162652015686, 0.46101799607276917, 0.42235398292541504, 0.4677119851112366, 0.43436622619628906, 0.5281707048416138, 0.3855609893798828, 0.5156357884407043, 0.3526361286640167, 0.5258020758628845, 0.439893901348114, 0.5277926921844482, 0.4466746151447296, 0.6029036045074463, 0.39088842272758484, 0.5850404500961304, 0.3694615364074707, 0.5851420164108276, 0.4305492043495178, 0.5862584114074707, 0.4451730251312256] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0.6585960984230042, 0.7824326753616333, 0.5312278270721436, 0.7473666667

 30%|██▉       | 49/164 [00:02<00:05, 19.28it/s]

[0.5898642539978027, 0.6811130046844482, 0.5035945177078247, 0.651731014251709, 0.4586855471134186, 0.576615571975708, 0.5161692500114441, 0.5085199475288391, 0.5925023555755615, 0.47898155450820923, 0.4550893008708954, 0.45306333899497986, 0.4371706247329712, 0.35767993330955505, 0.4339790344238281, 0.2987031042575836, 0.43411338329315186, 0.24658378958702087, 0.5187289118766785, 0.4335082173347473, 0.4995315372943878, 0.32532140612602234, 0.49113067984580994, 0.25765007734298706, 0.48368602991104126, 0.20018865168094635, 0.58469557762146, 0.4426819682121277, 0.5762867331504822, 0.3418367803096771, 0.5645474195480347, 0.2839771509170532, 0.5530348420143127, 0.23455575108528137, 0.6543520092964172, 0.47203195095062256, 0.6709002256393433, 0.4023572504520416, 0.674665629863739, 0.3566620647907257, 0.6756039261817932, 0.3146582543849945] [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 35%|███▌      | 58/164 [00:02<00:05, 20.19it/s]

[0.6459598541259766, 0.6798865795135498, 0.5420981645584106, 0.6019973754882812, 0.4466230273246765, 0.5105295181274414, 0.3462129831314087, 0.4557988941669464, 0.2769339084625244, 0.43347084522247314, 0.5734001994132996, 0.3383050262928009, 0.5484297871589661, 0.18136700987815857, 0.45626094937324524, 0.14210189878940582, 0.38310641050338745, 0.1480967104434967, 0.5916563868522644, 0.3722737431526184, 0.345100998878479, 0.33267077803611755, 0.31244173645973206, 0.42359745502471924, 0.3570238947868347, 0.46586889028549194, 0.5746421813964844, 0.4362890124320984, 0.3324025869369507, 0.4526028633117676, 0.3429124057292938, 0.5249244570732117, 0.4046729803085327, 0.5329487323760986, 0.5405034422874451, 0.5072116255760193, 0.35699254274368286, 0.5361764430999756, 0.3646323084831238, 0.5907598733901978, 0.4205895960330963, 0.5947246551513672] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0.478378027677536, 0.5190927386283875, 0.3973052203655243, 0.45746260881423

 39%|███▉      | 64/164 [00:02<00:05, 19.80it/s]

[0.4580802023410797, 0.6847779750823975, 0.34945112466812134, 0.581913948059082, 0.30136144161224365, 0.45413434505462646, 0.28011611104011536, 0.36228805780410767, 0.3003182113170624, 0.2955959737300873, 0.5369229316711426, 0.29168185591697693, 0.46786928176879883, 0.1607508510351181, 0.3657504916191101, 0.09680967032909393, 0.2836979031562805, 0.07447105646133423, 0.5966078042984009, 0.3193953335285187, 0.35572904348373413, 0.25315752625465393, 0.30250823497772217, 0.37355470657348633, 0.355024516582489, 0.42844048142433167, 0.6204158067703247, 0.37726324796676636, 0.3800058662891388, 0.3219600021839142, 0.3413199782371521, 0.42678844928741455, 0.40268421173095703, 0.4675937592983246, 0.6132514476776123, 0.4545291066169739, 0.42503997683525085, 0.4164472222328186, 0.3834128975868225, 0.4797567129135132, 0.4300174415111542, 0.5157726407051086] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0.529114842414856, 0.6102335453033447, 0.42444705963134766, 0.562918

 43%|████▎     | 70/164 [00:03<00:04, 21.37it/s]

[0.5812305808067322, 0.7704692482948303, 0.4660126566886902, 0.6803028583526611, 0.43155014514923096, 0.552024781703949, 0.4814522862434387, 0.46265649795532227, 0.5313347578048706, 0.4240787625312805, 0.38266170024871826, 0.4853869080543518, 0.4062560498714447, 0.3692730665206909, 0.4384841322898865, 0.28534871339797974, 0.4756695628166199, 0.21312415599822998, 0.4623872935771942, 0.48793521523475647, 0.4508167505264282, 0.3582107126712799, 0.44984301924705505, 0.2839413285255432, 0.45601290464401245, 0.20770037174224854, 0.5429953932762146, 0.5088257789611816, 0.581678032875061, 0.4178440570831299, 0.5658025145530701, 0.5196154117584229, 0.5375351905822754, 0.5689151883125305, 0.616639256477356, 0.5387991666793823, 0.6396293044090271, 0.47999492287635803, 0.6223883628845215, 0.5409630537033081, 0.5924278497695923, 0.5781542062759399] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0.5564817190170288, 0.6847332715988159, 0.44443756341934204, 0.66266345977783

 47%|████▋     | 77/164 [00:03<00:03, 24.34it/s]

[0.48362821340560913, 0.7024654150009155, 0.3367109000682831, 0.6501611471176147, 0.20471814274787903, 0.5532761812210083, 0.13008812069892883, 0.451069712638855, 0.20061719417572021, 0.3983551561832428, 0.3854915201663971, 0.27771231532096863, 0.46436363458633423, 0.1015784740447998, 0.44457489252090454, 0.1462944895029068, 0.4144396185874939, 0.23768217861652374, 0.5137916207313538, 0.29023241996765137, 0.5983940362930298, 0.0938815176486969, 0.5619768500328064, 0.20954740047454834, 0.5246772170066833, 0.3093961179256439, 0.6241361498832703, 0.3359617590904236, 0.7000964283943176, 0.15565228462219238, 0.6588655114173889, 0.25445556640625, 0.6157867908477783, 0.3577468693256378, 0.7206602692604065, 0.4108601212501526, 0.7707183957099915, 0.2778588533401489, 0.7308973073959351, 0.33098673820495605, 0.6835439205169678, 0.40462636947631836] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 53%|█████▎    | 87/164 [00:03<00:02, 26.92it/s]

[0.5529001951217651, 0.7683892250061035, 0.46352535486221313, 0.668368935585022, 0.4221784472465515, 0.5740863680839539, 0.374187707901001, 0.5134506821632385, 0.32924890518188477, 0.46703848242759705, 0.6250878572463989, 0.5270214676856995, 0.5324058532714844, 0.42507287859916687, 0.44264325499534607, 0.4145458936691284, 0.3748035430908203, 0.4317329227924347, 0.6411893963813782, 0.5311648845672607, 0.5412688851356506, 0.4000643193721771, 0.4382377862930298, 0.3975827693939209, 0.3663679361343384, 0.4268132448196411, 0.6249592900276184, 0.5422942042350769, 0.5471940636634827, 0.3981019854545593, 0.4474078118801117, 0.394228458404541, 0.37903887033462524, 0.41500765085220337, 0.5760582685470581, 0.5566409826278687, 0.5146704912185669, 0.4379933476448059, 0.44479167461395264, 0.41404882073402405, 0.3903028666973114, 0.41812846064567566] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 57%|█████▋    | 93/164 [00:04<00:03, 19.11it/s]

[0.6723352074623108, 0.6611356735229492, 0.5426275134086609, 0.5163910984992981, 0.4607275128364563, 0.4177020788192749, 0.3887791335582733, 0.3546658158302307, 0.3402724266052246, 0.2998146414756775, 0.7131018042564392, 0.3023119866847992, 0.5694360733032227, 0.22378994524478912, 0.4581925570964813, 0.22994773089885712, 0.3770759701728821, 0.2563829720020294, 0.7475214004516602, 0.3059634268283844, 0.5721995830535889, 0.19524577260017395, 0.4474661648273468, 0.2105506807565689, 0.3632168471813202, 0.25049957633018494, 0.7487090826034546, 0.3235747814178467, 0.593564510345459, 0.20162343978881836, 0.4638723134994507, 0.2060297131538391, 0.3764282166957855, 0.24342676997184753, 0.7092912197113037, 0.35561811923980713, 0.5889872312545776, 0.24130278825759888, 0.4948377311229706, 0.2217349112033844, 0.4230533838272095, 0.23210281133651733] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.516436755657196, 0.706180989742279, 0.4771978259086609, 0.6722483038902283

 60%|██████    | 99/164 [00:04<00:03, 17.95it/s]

[0.6615634560585022, 0.5496257543563843, 0.5852154493331909, 0.4987216591835022, 0.5017932057380676, 0.41624167561531067, 0.43706071376800537, 0.36391592025756836, 0.38362735509872437, 0.3167240619659424, 0.5725229978561401, 0.3209543526172638, 0.4683310091495514, 0.212743878364563, 0.36749571561813354, 0.16270211338996887, 0.28329896926879883, 0.14101994037628174, 0.5777557492256165, 0.3170463740825653, 0.4555637538433075, 0.19559943675994873, 0.34045228362083435, 0.15399721264839172, 0.24829727411270142, 0.1426372230052948, 0.562831461429596, 0.33341896533966064, 0.44853657484054565, 0.20624732971191406, 0.3381657004356384, 0.1619109809398651, 0.24920880794525146, 0.14436198770999908, 0.5284304022789001, 0.36868447065353394, 0.44399112462997437, 0.2686130702495575, 0.36827266216278076, 0.21720364689826965, 0.3025130033493042, 0.18511082231998444] [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.4975072145462036, 0.5840923190116882, 0.41300415992736816, 0.5

 63%|██████▎   | 103/164 [00:04<00:03, 17.69it/s]

[0.44464433193206787, 0.8348347544670105, 0.3927702307701111, 0.7892735600471497, 0.3944172263145447, 0.7207038998603821, 0.45589935779571533, 0.6712180972099304, 0.5079100131988525, 0.6433561444282532, 0.4266257584095001, 0.6540637612342834, 0.4396592676639557, 0.5827581882476807, 0.45391348004341125, 0.5323827862739563, 0.4690147042274475, 0.4825182557106018, 0.4844493567943573, 0.658950924873352, 0.48311111330986023, 0.5800053477287292, 0.4790968596935272, 0.5216279625892639, 0.48097655177116394, 0.4636598229408264, 0.5349084138870239, 0.683268666267395, 0.5462257266044617, 0.6438908576965332, 0.5047104358673096, 0.702838659286499, 0.46997782588005066, 0.7477831244468689, 0.5795606970787048, 0.7241734862327576, 0.5888375639915466, 0.6859880089759827, 0.5507510304450989, 0.7174735069274902, 0.5131593942642212, 0.7482370138168335] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


 68%|██████▊   | 111/164 [00:05<00:02, 18.81it/s]

[0.5224847793579102, 0.7395172119140625, 0.4084727168083191, 0.7047058343887329, 0.35633599758148193, 0.582256019115448, 0.42531102895736694, 0.4899694621562958, 0.5248413681983948, 0.47124049067497253, 0.3532281816005707, 0.48350387811660767, 0.3287174105644226, 0.38841068744659424, 0.33712220191955566, 0.40902480483055115, 0.3645598292350769, 0.47154000401496887, 0.43334197998046875, 0.4562109112739563, 0.42075419425964355, 0.33965539932250977, 0.4159013330936432, 0.37328988313674927, 0.42689821124076843, 0.44025006890296936, 0.5068325400352478, 0.4555426239967346, 0.5067389011383057, 0.33750608563423157, 0.4895295798778534, 0.3821414113044739, 0.4927947521209717, 0.4556474983692169, 0.5834681391716003, 0.4711948335170746, 0.581541121006012, 0.3846307694911957, 0.554517388343811, 0.4080398678779602, 0.5376260876655579, 0.46373170614242554] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.33167845010757446, 0.930631160736084, 0.23674799501895905, 0.85510480

 71%|███████▏  | 117/164 [00:05<00:02, 19.89it/s]

[0.7662972807884216, 0.3428369164466858, 0.5785499215126038, 0.3158301115036011, 0.40731650590896606, 0.42262017726898193, 0.31548672914505005, 0.5657051801681519, 0.266185998916626, 0.6868782043457031, 0.3305077850818634, 0.444670706987381, 0.2108423411846161, 0.5802685618400574, 0.14033272862434387, 0.6577482223510742, 0.08071792125701904, 0.7193601131439209, 0.41187942028045654, 0.5240310430526733, 0.35163772106170654, 0.7173985838890076, 0.32789847254753113, 0.8350338339805603, 0.3126968741416931, 0.9130780696868896, 0.5158654451370239, 0.5894419550895691, 0.46985384821891785, 0.723901629447937, 0.5029939413070679, 0.6788281202316284, 0.53754723072052, 0.6240941286087036, 0.6192155480384827, 0.6397748589515686, 0.5630890727043152, 0.7247921228408813, 0.5937315225601196, 0.6890596747398376, 0.6245477795600891, 0.6516716480255127] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.8133652210235596, 0.614607572555542, 0.7674438953399658, 0.42727410793304443, 

 76%|███████▌  | 125/164 [00:05<00:02, 18.76it/s]

[0.4118657112121582, 0.844829797744751, 0.30391019582748413, 0.7386189699172974, 0.28566303849220276, 0.5165412425994873, 0.29870283603668213, 0.3369304835796356, 0.32524240016937256, 0.2140367329120636, 0.5020291805267334, 0.46047237515449524, 0.43149334192276, 0.31700944900512695, 0.37741923332214355, 0.26661765575408936, 0.3688163459300995, 0.21862539649009705, 0.6324381232261658, 0.4931725859642029, 0.5282403826713562, 0.429002046585083, 0.46405500173568726, 0.5502960681915283, 0.46733036637306213, 0.6394274830818176, 0.7305612564086914, 0.5401021838188171, 0.6272861957550049, 0.4669145941734314, 0.5482298135757446, 0.5675843358039856, 0.5355193018913269, 0.6437305212020874, 0.8147883415222168, 0.6001654863357544, 0.7548484802246094, 0.5024694800376892, 0.6724441647529602, 0.5440493822097778, 0.6368616223335266, 0.5788705348968506] [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.7371671199798584, 0.6713453531265259, 0.6596923470497131, 0.658568024635314

 79%|███████▉  | 130/164 [00:06<00:01, 19.21it/s]

[0.7260932326316833, 0.697185754776001, 0.7022945880889893, 0.5488219857215881, 0.5555932521820068, 0.40673261880874634, 0.38622981309890747, 0.3452538549900055, 0.2596355378627777, 0.2957760989665985, 0.6220413446426392, 0.34536585211753845, 0.36818772554397583, 0.3062154948711395, 0.22842136025428772, 0.30576378107070923, 0.12635910511016846, 0.3032735586166382, 0.5985187888145447, 0.4543446898460388, 0.33042338490486145, 0.4110323488712311, 0.339687705039978, 0.45022764801979065, 0.3910677433013916, 0.47000548243522644, 0.5654960870742798, 0.5708134770393372, 0.30518919229507446, 0.5172732472419739, 0.34077736735343933, 0.5563809871673584, 0.4132267236709595, 0.5765944719314575, 0.5304778814315796, 0.6808887124061584, 0.31850361824035645, 0.6290504932403564, 0.28441619873046875, 0.6255921125411987, 0.28966009616851807, 0.6195895671844482] [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.49908536672592163, 0.7027769088745117, 0.4155367910861969, 0.67185693

 82%|████████▏ | 134/164 [00:06<00:01, 18.22it/s]

[0.7648023962974548, 0.5939093828201294, 0.701485276222229, 0.47938963770866394, 0.5860987901687622, 0.4564594626426697, 0.4886336922645569, 0.4857836067676544, 0.4336656630039215, 0.5190251469612122, 0.5267980098724365, 0.4896930754184723, 0.37373441457748413, 0.4961773753166199, 0.2915940284729004, 0.5033100247383118, 0.22813314199447632, 0.5160210728645325, 0.5190296769142151, 0.5744819641113281, 0.3650699257850647, 0.5688414573669434, 0.2688457667827606, 0.5701708197593689, 0.20315253734588623, 0.5835334062576294, 0.5326601266860962, 0.646325945854187, 0.44890427589416504, 0.6273330450057983, 0.48231223225593567, 0.6043040752410889, 0.5259255170822144, 0.6006433367729187, 0.5606436133384705, 0.7037745118141174, 0.5049182772636414, 0.6670159101486206, 0.5319885611534119, 0.6501966118812561, 0.5663723945617676, 0.6480245590209961] [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.48071664571762085, 0.6547633409500122, 0.36362266540527344, 0.5656954050064087

 85%|████████▍ | 139/164 [00:06<00:01, 18.47it/s]

[0.5791396498680115, 0.8936562538146973, 0.4256811738014221, 0.8797670006752014, 0.2549991011619568, 0.7795714735984802, 0.16417884826660156, 0.6978318691253662, 0.23574452102184296, 0.6670698523521423, 0.3094879984855652, 0.6071086525917053, 0.23076164722442627, 0.5276735424995422, 0.27547332644462585, 0.6247996687889099, 0.3317471146583557, 0.7152727246284485, 0.41285330057144165, 0.5634022355079651, 0.3570072650909424, 0.5044505000114441, 0.3964831233024597, 0.6558539867401123, 0.4449044466018677, 0.7562329769134521, 0.5334563851356506, 0.5427501797676086, 0.4873233139514923, 0.4324859380722046, 0.4741355776786804, 0.5375653505325317, 0.47785070538520813, 0.6205472946166992, 0.6572122573852539, 0.5455261468887329, 0.7036545276641846, 0.408893883228302, 0.7351161241531372, 0.3234128952026367, 0.7631839513778687, 0.23631632328033447] [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 90%|████████▉ | 147/164 [00:06<00:00, 18.35it/s]

[0.4025712013244629, 0.5869166851043701, 0.4375220537185669, 0.522254228591919, 0.5011380314826965, 0.4978063702583313, 0.5560323596000671, 0.5066971778869629, 0.5907210111618042, 0.523162841796875, 0.5285419225692749, 0.5317249298095703, 0.594545841217041, 0.5259853601455688, 0.6381144523620605, 0.5236724019050598, 0.6700278520584106, 0.5221999287605286, 0.5290641784667969, 0.5704972743988037, 0.5946837663650513, 0.5639264583587646, 0.6356530785560608, 0.556513249874115, 0.6702843308448792, 0.5516738891601562, 0.5267694592475891, 0.6048494577407837, 0.5903812050819397, 0.596366822719574, 0.632245659828186, 0.5849146842956543, 0.6661837100982666, 0.5781964659690857, 0.522779643535614, 0.6322373151779175, 0.5783458948135376, 0.6181328296661377, 0.6143463253974915, 0.6030421853065491, 0.643071711063385, 0.5925341248512268] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0.659817636013031, 0.7055771350860596, 0.7152523994445801, 0.5528687238693237, 0.67378699779

 94%|█████████▍| 154/164 [00:07<00:00, 18.76it/s]

[0.47691941261291504, 0.7220901846885681, 0.4109916090965271, 0.6569188833236694, 0.4090764820575714, 0.5418635010719299, 0.47629427909851074, 0.4535200595855713, 0.537406325340271, 0.3900882601737976, 0.37297624349594116, 0.46395376324653625, 0.38338690996170044, 0.41171514987945557, 0.375829815864563, 0.48565569519996643, 0.363042950630188, 0.5369953513145447, 0.4320586621761322, 0.46602949500083923, 0.44608330726623535, 0.4027238190174103, 0.4247105121612549, 0.49308809638023376, 0.3995841145515442, 0.5473983287811279, 0.4899352788925171, 0.4852662682533264, 0.506833553314209, 0.4309278130531311, 0.47783714532852173, 0.5107895135879517, 0.4487495720386505, 0.5549561381340027, 0.542538046836853, 0.515808641910553, 0.5471177697181702, 0.48352673649787903, 0.5181245803833008, 0.5462149977684021, 0.4944431781768799, 0.5775335431098938] [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


100%|██████████| 164/164 [00:07<00:00, 20.96it/s]


In [ ]:
import joblib

output_dir = f"/content/drive/MyDrive/IS4242/dump/"
joblib.dump(test_data, output_dir+'data_svm_test.pkl')
joblib.dump(test_label, output_dir+'labels_svm_test.pkl')

['/content/drive/MyDrive/IS4242/dump/labels_svm_test.pkl']

In [ ]:
labels = np.array(labels)
test_label = np.array(test_label)

In [ ]:
x_train = np.array(data)
x_test = np.array(test_data)
x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
print(x_train.shape)
print(x_test.shape)

(2453, 42, 1)
(44, 42, 1)


#### SVM - linear


In [ ]:
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [ ]:
# linear model

model_linear = SVC(kernel='linear')
model_linear.fit(x_train.reshape((x_train.shape[0],42)), np.argmax(labels, axis=1))

# predict
y_pred = model_linear.predict(x_test.reshape((x_test.shape[0],42)))

##### Evaluation

In [ ]:
# confusion matrix and accuracy

# accuracy
print("accuracy:", metrics.accuracy_score(y_true=np.argmax(test_label, axis=1), y_pred=y_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=np.argmax(test_label, axis=1), y_pred=y_pred))

accuracy: 0.8409090909090909 

[[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(np.argmax(test_label, axis=1), y_pred))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86         3
           1       1.00      1.00      1.00         1
           2       1.00      0.50      0.67         2
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         2
           8       1.00      1.00      1.00         2
           9       0.00      0.00      0.00         1
          10       0.75      1.00      0.86         3
          11       0.50      1.00      0.67         1
          12       0.00      0.00      0.00         2
          13       0.67      1.00      0.80         2
          14       1.00      1.00      1.00         3
          16       1.00      0.67      0.80         3
          17       0.50      1.00      0.67         1
          18       0.67      0.67      0.67         3
          19       0.50    

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


#### SVM - rbf non linear 

In [ ]:
# non-linear model
# using rbf kernel, C=1, default value of gamma

# non-linear model

non_linear = SVC(kernel='rbf')
non_linear.fit(x_train.reshape((x_train.shape[0],42)), np.argmax(labels, axis=1))

# predict
y_pred = non_linear.predict(x_test.reshape((x_test.shape[0],42)))

##### Evaluation

In [ ]:
# confusion matrix and accuracy

# accuracy
print("accuracy:", metrics.accuracy_score(y_true=np.argmax(test_label, axis=1), y_pred=y_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=np.argmax(test_label, axis=1), y_pred=y_pred))

accuracy: 0.8409090909090909 

[[3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(np.argmax(test_label, axis=1), y_pred))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86         3
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         1
           7       1.00      1.00      1.00         2
           8       1.00      1.00      1.00         2
           9       0.00      0.00      0.00         1
          10       1.00      0.67      0.80         3
          11       0.50      1.00      0.67         1
          12       1.00      0.50      0.67         2
          13       1.00      1.00      1.00         2
          14       1.00      1.00      1.00         3
          16       0.60      1.00      0.75         3
          17       0.33      1.00      0.50         1
          18       0.67      0.67      0.67         3
          19       0.00    

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from joblib import dump, load
s = dump(non_linear,'/content/drive/MyDrive/SVM/model.joblib')
